#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
SOURCE_ENV_PATH="$HOME/ENV"

if [ -f "$SOURCE_ENV_PATH" ] && [ ! -f "$APP/ENV"  ] ; then
  echo "-----> Installing ENV in build environment ..."
  dokku config:set  "$SOURCE_ENV_PATH" 
fi
